# mint run xcodegen generate

name: LabeledDatasetCurator
options:
  bundleIdPrefix: com.akitora
  deploymentTarget:
    macOS: "15.2"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

targets:
  LabeledDatasetCurator:
    type: tool
    platform: macOS
    sources:
      - path: main.swift
    dependencies:
      - target: OvRClassification
      - target: SLImageLoader
      - target: SLFileManager
      - target: CatAPIClient
      - target: SLDuplicateChecker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitora.LabeledDatasetCurator
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  LabeledDatasetCuratorTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: LabeledDatasetCuratorTests
    dependencies:
      - target: OvRClassification
      - target: CatAPIClient
      - target: SLFileManager
      - target: SLImageLoader
      - target: SLDuplicateChecker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.LabeledDatasetCuratorTests
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  OvRClassification:
    type: framework
    platform: macOS
    sources:
      - path: OvRClassification
        excludes:
          - "**/*.md"
    dependencies:
      - target: SLFileManager
      - target: SLImageLoader
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitora.OvRClassification
        PRODUCT_NAME: OvRClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  CatAPIClient:
    type: framework
    platform: macOS
    sources:
      - path: CatAPIClient
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitora.CatAPIClient
        PRODUCT_NAME: CatAPIClient
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
    dependencies: []

  SLFileManager:
    type: framework
    platform: macOS
    sources:
      - path: SLFileManager
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitora.SLFileManager
        PRODUCT_NAME: SLFileManager
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
    dependencies: []

  SLImageLoader:
    type: framework
    platform: macOS
    sources:
      - path: SLImageLoader
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitora.SLImageLoader
        PRODUCT_NAME: SLImageLoader
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
    dependencies: []

  SLDuplicateChecker:
    type: framework
    platform: macOS
    sources:
      - path: SLDuplicateChecker
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitora.SLDuplicateChecker
        PRODUCT_NAME: SLDuplicateChecker
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
    dependencies:
      - target: SLFileManager
