# mint run xcodegen generate

name: LabeledDatasetCurator
options:
  deploymentTarget:
    macOS: "15.2"
  createIntermediateGroups: true

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: 5.9
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    COREML_CODEGEN_LANGUAGE: Swift
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

packages:
  LabeledDatasetCurator:
    path: .
    products:
      - SLFileManager
      - SLImageLoader
      - SLDuplicateChecker
      - SLClassifier
      - CatAPIClient

targets:
  LabeledDatasetCurator:
    type: tool
    platform: macOS
    sources:
      - path: main.swift
    dependencies:
      - package: LabeledDatasetCurator
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.LabeledDatasetCurator
        MACOSX_DEPLOYMENT_TARGET: "15.2"

schemes:
  LabeledDatasetCurator:
    build:
      targets:
        LabeledDatasetCurator: all
    run:
      config: Debug
