# mint run xcodegen generate

name: OvRImageClassifierTrainer
options:
  bundleIdPrefix: com.akitora
  deploymentTarget:
    macOS: "15.2"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

targets:
  OvRImageClassifierTrainer:
    type: tool
    platform: macOS
    sources:
      - path: main.swift
    dependencies:
      - target: OvRClassification
      - target: CTImageLoader
      - target: CTFileManager
      - target: CatAPIClient
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitora.ovr-image-classifier-trainer
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  OvRImageClassifierTrainerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: OvRImageClassifierTrainerTests
    dependencies:
      - target: OvRClassification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.OvRImageClassifierTrainerTests
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  OvRClassification:
    type: framework
    platform: macOS
    sources:
      - path: OvRClassification
        excludes:
          - "**/*.md"
    dependencies:
      - target: CatAPIClient
      - target: CTFileManager
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitora.ovr-classification
        PRODUCT_NAME: OvRClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  CatAPIClient:
    type: framework
    platform: macOS
    sources:
      - path: CatAPIClient
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitora.cat-api-client
        PRODUCT_NAME: CatAPIClient
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
    dependencies: []

  CTFileManager:
    type: framework
    platform: macOS
    sources:
      - path: CTFileManager
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitora.ct-file-manager
        PRODUCT_NAME: CTFileManager
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
    dependencies: []

  CTImageLoader:
    type: framework
    platform: macOS
    sources:
      - path: CTImageLoader
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitora.ct-image-loader
        PRODUCT_NAME: CTImageLoader
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
    dependencies: []
