name: ImageClassifierTrainer CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  # Mintのセットアップ
  setup-mint:
    name: Setup Mint
    uses: ./.github/workflows/setup-mint.yml
    permissions:
      contents: read

  # ビルド
  build-package:
    name: Build Package
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Package
        run: swift build

  # ユニットテスト
  run-tests:
    name: Run Unit Tests
    needs: setup-mint
    uses: ./.github/workflows/run-tests.yml

  # コード品質チェック
  code-quality:
    name: Code Quality Check
    needs: setup-mint
    uses: ./.github/workflows/code-quality.yml