name: ImageClassifierTrainer CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  # Mintのセットアップ
  setup-mint:
    name: Setup Mint
    uses: ./.github/workflows/setup-mint.yml
    permissions:
      contents: read

  # コード品質チェック
  code-quality:
    name: Code Quality Check
    needs: setup-mint
    uses: ./.github/workflows/code-quality.yml