name: Run Unit Tests

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: macos-15
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Mint packages
        uses: actions/cache@v4
        with:
          path: ${{ env.MINT_PATH }}
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Generate Xcode Project
        run: mint run xcodegen generate

      - name: Run Unit Tests
        run: |
          set -o pipefail
          xcodebuild test \
            -project "LabeledDatasetCurator.xcodeproj" \
            -scheme "LabeledDatasetCurator" \
            -destination "platform=macOS" \
            -enableCodeCoverage NO \
            MACOSX_DEPLOYMENT_TARGET=15.2 \
            | xcbeautify 