name: Test Reporter

on:
  workflow_call:
    inputs:
      test_run_outcome:
        required: true
        type: string
    outputs:
      overall_test_result:
        description: "全体のテスト結果 (success または failure)"
        value: ${{ jobs.report.outputs.overall_result }}

jobs:
  report:
    runs-on: ubuntu-latest
    outputs:
      overall_result: ${{ steps.set_overall_status.outputs.result }}
    steps:
      - name: Check test job outcome
        id: set_overall_status
        run: |
          echo "Overall Test Run Outcome: ${{ inputs.test_run_outcome }}"

          if [[ "${{ inputs.test_run_outcome }}" == "success" ]]; then
            echo "Test run succeeded."
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "Test run failed or was skipped."
            echo "result=failure" >> $GITHUB_OUTPUT
          fi 